# Generated by Django 5.0.4 on 2024-06-29 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_sale_report_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='supply',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supply', to_field='name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supply'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
