# Generated by Django 5.0.4 on 2024-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_oldstock_supply_display_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldstock',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
