# Generated by Django 5.0.4 on 2024-06-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_oldstock_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
